BEGIN TRANSACTION;
CREATE TABLE 'users' (
  'Id' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  'user_id' TEXT NOT NULL,
  'lang' BOOLEAN NOT NULL,
  'name' TEXT NOT NULL,
  'sleep_time' TEXT NOT NULL,
  'sleep_hours' TEXT NOT NULL
);
COMMIT;
